# Generated by Django 4.2.13 on 2026-06-05 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venda_cancelado_por_venda_data_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_operacional',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
