# Generated by Django 4.2.13 on 2026-06-05 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_senha_operacional_venda_autorizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
