# Generated by Django 4.2.13 on 2026-06-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venda_data_finalizacao_venda_finalizado_por'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='vendas_status_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data'], name='vendas_data_idx'),
        ),
    ]
